// AUTH
export const LOGGED_IN = 'LOGGED_IN';
export const LOG_OUT = 'LOG_OUT';

// UNIVERSITY
export const SET_UNIVERSITIES = 'SET_UNIVERSITIES';
export const SET_UNIVERSITY = 'SET_UNIVERSITY';
export const SEARCH_UNIVERSITY = 'SEARCH_UNIVERSITY';
export const SET_CURRENT_UNIVERSITY = 'SET_CURRENT_UNIVERSITY';
export const ADD_UNVERSITY_TO_FAVORITE = 'ADD_UNVERSITY_TO_FAVORITE';

// USER
export const UPDATE_USER = 'UPDATE_USER';
