export enum QueryActions {
  AUTH_GET_LOGGED = "AUTH/GET_LOGGED",
  AUTH_LOGIN = "AUTH/LOGIN",

  USER_GET_LIST = "USER/GET_LIST",
  USER_GET = "USER/GET",
  USER_UPDATE = "USER/UPDATE",
  USER_DEACTIVATE = "USER/DEACTIVATE",
}
