export enum QueryActions {
  AUTH_GET_LOGGED = "AUTH/GET_LOGGED",
  AUTH_LOGIN = "AUTH/LOGIN",

  USER_GET = "USER/GET",
  USER_CREATE = "USER/CREATE",

  PROFILE_UPDATE = "PROFILE/UPDATE",

  COUNTRY_GET = "COUNTRY/GET",
}
